### ISSUE TITLE
App fails to start - I only see the "This app requires WiFi connection" toast.

### ISSUE THREAD

**Issue by jaimet** [izivkov/RemoteVideoCam#8] opened 2022-10-28 16:04 UTC
I'm running RemoteVideoCam on 3 different phones all connected to the same broadcast domain:

Motorola Moto G (XT1032) works perfectly
Samsung Galaxy S4 (SGH-M919) works perfectly
OnePlus 5T (A5010) fails to start - all I get is the ["This app requires WiFi connection..." toast](https://github.com/izivkov/RemoteVideoCam/blob/master/app/src/main/java/org/avmedia/remotevideocam/MainActivity.kt#L44).

All three phones are using [v2.7 from f-droid](https://f-droid.org/repo/org.avmedia.remotevideocam_27.apk) (apk md5sum starts `a140...`).

Would a logcat help?

**Comment by izivkov** [comment] 2022-10-28 17:58
Are you sure your OnePlus is connected to your WiFi network? If it is,
maybe the telecom network takes precidence. Can you temporarily disable
your telephone network and try again?

**Comment by izivkov** [comment] 2022-10-28 21:23
One thing you can try is to go the Android Settings -> Apps and
Notification -> RemoteVideoCam and Clear Storage. Then run the app again.

I will check why the app does not start after disconnecting and
connecting back on WiFi.

Thanks for reporting.

Ivo

**Comment by jaimet** [comment] 2022-10-29 11:30
> Are you sure your OnePlus is connected to your WiFi network? If it is, maybe the telecom network takes precidence. Can you temporarily disable your telephone network and try again?

This is really weird. I temporarily disabled my telephone network and I was able to start the app successfully. I then thought "Great - that is the solution." But...

Then I re-enabled my telephone network and the app did **_not_** start again.

Then I re-disabled my telephone network (hence only wifi now) and still the app did **_not_** start. Huh?

Disable and re-enable wifi (telephone network still disabled from previous step hence **_only_** wifi is connected) - still the app does **_not_** start. Huh?

After a "Clear cache", still the app does **_not_** start.
After a "Clear storage", the app **_does_** start.

[Here](https://github.com/izivkov/RemoteVideoCam/files/9893563/logcat.txt) is a logcat "failure" session (piped through "grep remotevideocam") - hopefully this helps.

**Comment by izivkov** [comment] 2022-10-29 13:08
Thanks, I'll look into it.

**Comment by izivkov** [comment] 2022-12-20 14:42
This happens when the phone is using its mobile connection instead of the WiFi connection. It is different for different phones, but maybe disabling your mobile connection temporary will solve the problem. The app has no control over that, so I am closing this issue.

**Closed by izivkov** 2022-12-20 14:42 UTC

**Comment by Quantum-Future** [comment] 2024-06-06 11:13
I have the same problem on a Xiaomi Mi 9 Lite (Android 9).
I have only WiFi active. Cellular data is not active and also disabled on the properties of the app (No mobile data usage).

**Comment by izivkov** [comment] 2024-06-07 22:15
Is it working with other phones for you?

**Comment by Quantum-Future** [comment] 2024-07-08 04:51
I tested on a newer Xiaomi phone with Android 13 and yes, it works.
Well, at least the error message does not appears, but I couldn't test video functionality because I had no other phone available at that moment.

**Comment by Quantum-Future** [comment] 2024-07-21 07:58
I upgraded to Ver 3.2 and noticed this:
- When the app starts with WiFi disabled, the message about WiFi required appears.
- Then I enabled WiFi and started the app again, but the same message appears (does not detect that WiFi is active).
- I forced the stop of the app and then re-startet it.  Now it detects that WiFi is active and works as expected.

I hope this helps to solve the problem in the next version.

**Comment by izivkov** [comment] 2024-07-21 15:16
Is the OnePlus connected to WiFi? Are you running only 2 phones at a time?

**Comment by Quantum-Future** [comment] 2024-07-22 20:46
I don't have a OnePlus, I have a Xiaomi.
The comment about the OnePlus and other 2 phones, was from another user (jaimet).
I started to comment in this thread, because I had the same problem as Jaimet.

My previous post was using only the Xiaomi.

**Comment by izivkov** [comment] 2024-07-23 03:57
I'm not sure how to reproduce the issue. I'll live it open for a while, to
see if anyone can pick it up and try to address it.

**Comment by Quantum-Future** [comment] 2024-07-23 05:40
I think the problem does not happen on all Android versions. As I said before, I tested it on another Xiaomi phone with Android 13, and this message doesn't appear.
The problem happens on a Xiaomi with Android 9.
Can you obtain a phone with android 9 to test it? 

PS: This issue is not open.
